### ISSUE TITLE
Routing labels/text line break on mobile 

### ISSUE THREAD

**Issue by nicoelzer** [levelkdev/dxswap-dapp#193]
![swapr_mobile](https://user-images.githubusercontent.com/1383195/110211030-0b10ed00-7eae-11eb-9ff8-46fc870886cb.png)

**Comment by 0xVenky** [comment]
I think this is fixed in the latest Alpha 3. https://gateway.pinata.cloud/ipfs/QmanWVMtwZqJdgv5tajpCHVrB1tcK2HbgaGKZ8PhXDiiSU/#/swap But I am guessing we need to test this on multiple devices of different sizes.

![image](https://user-images.githubusercontent.com/55109759/110592502-a63de700-817a-11eb-8f1a-f683ab05ff9c.png)
