### ISSUE TITLE
Do not display the default 0.25% fees if the fees do not load.

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#212]
HAUS-WETH pair had 3% fees, so the value in the screenshot should be 3.25% but it says 0.5% until the fees loads. 

![image](https://user-images.githubusercontent.com/55109759/113289430-7eaceb00-92f0-11eb-85d3-095aad138af3.png)

**Comment by luzzif** [comment]
Should be fixed in the latest build of swapr.dev. In Swapr's case, the fee has to be dynamically fetched, and prior to the fix, the pair was assigned the default swap fee of .25% if the true one didn't load yet. As of now, the pair is not considered loaded if the swap fee is missing, and the default platform swap fee of other platforms is used when performing ecorouting.
