### ISSUE TITLE
Each 0 added after decimal point gives random Price impact

### ISSUE THREAD

**Issue by snufkin0x** [levelkdev/dxswap-dapp#252]
Tested on both Mainnet and xDai network.

For example, when swapping xDai to WETH and entering 0.1 in WETH amount, then adding 0's after the decimal and seeing how the price impact changes. Theoretically it should go lower and lower. 0.1 gives 0.13%, but 0.01 gives 0.18%. But then at 0.000001 it gives a 14.65% price impact. Then again another 0 added and price impact is 1.46%. All of the rates for each decimal are for Honeyswap. Manually changing to Swapr or Baoswap, the price impact of 0.000001 WETH is back to normal <0.01%. For last two 0's it switches to Baoswap automatically, but the price impact is 18.90% and 34.97% respectively.

![Screenshot 2021-04-24 155826](https://user-images.githubusercontent.com/82238502/115967391-1215bc80-a53b-11eb-89b3-111386d2fb19.png)

**Comment by luzzif** [comment]
Uniswap seems to have the same "issue" (which I don't think is an issue at all). 
I've noticed that changing the input amount also result in different routes getting picked. It's possible that given an increased price impact, more output amount is still taken out of the trade using the new route, possibly because the asset used to route through simply offers a better price, which offsets the increased slippage.
I've noticed the behavior is as expected as long as the same route is applied (that is, the price impact becomes smaller the less input amount is used).
