### ISSUE TITLE
Mobile navigation update

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#280]
Created a mobile design for the navigation and updated network switcher

https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=3562%3A0
![image](https://user-images.githubusercontent.com/25611956/122189792-857be080-ce91-11eb-924c-b2ceac7b4073.png)

**Comment by alexcherman** [comment]
Hey @zamli, would you like me to merge this task with the "network switcher redesign" task(https://github.com/levelkdev/dxswap-dapp/pull/276)? Because looking at this screenshot I see a new network switcher design. It looks like these tasks are connected. I prefer to keep pull requests, as small as possible, but it looks like you I to merge them. What do you think about this?

**Comment by zamli** [comment]
> Hey @zamli, would you like me to merge this task with the "network switcher redesign" task(#276)? Because looking at this screenshot I see a new network switcher design. It looks like these tasks are connected. I prefer to keep pull requests, as small as possible, but it looks like you I to merge them. What do you think about this?

We could 100% merge these two. They are indeed connected. one is desktop one is for mobile.

**Comment by alexcherman** [comment]
@zamli Can we close it?
