### ISSUE TITLE
Common bases border/bg

### ISSUE THREAD

**Issue by zamli** [levelkdev/dxswap-dapp#339]
Give common bases a bg and make as the whole modal as close to the design as possible
![image](https://user-images.githubusercontent.com/25611956/132677858-85979b79-2bf7-43d8-9f0e-8cf8c69d9ebe.png)

https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=4549%3A16934

**Comment by Mi-Lan** [comment]
@zamli Hey men I was working on this today almost done. I have one suggestion.

https://user-images.githubusercontent.com/33226956/132745811-fb2f0148-959f-4f55-b222-b9b5ef701029.mov

You see how on uniswap they have this hover animation. Would it make sense to have something similar for swapr?

**Comment by Mi-Lan** [comment]
Also current hover for select token items doesn't seem optimal because it darkens just certain proerties and is not applied to all icons just a couple .
https://user-images.githubusercontent.com/33226956/132748720-4f9dfac5-578b-4e55-932e-c1885d093f10.mov
I would suggest we either remove it everywhere and do what Uniswap did like this:

https://user-images.githubusercontent.com/33226956/132748965-b1a8939f-4249-4eb7-8588-5b42ff910a43.mov

Or I can adjust current implantation to work with darkening like it was imagined....

**Comment by 0xVenky** [comment]
> @zamli Hey men I was working on this today almost done. I have one suggestion.
> 
>  Screen.Recording.2021-09-09.at.20.52.57.mov 
> You see how on uniswap they have this hover animation. Would it make sense to have something similar for swapr?

Totally makes sense.. :) We should do similar. :)

**Comment by 0xVenky** [comment]
Closing this, went as part of Beta 8.
