### ISSUE TITLE
Pair that I am Providing Liquidity To is Not Showing in "Pools"

### ISSUE THREAD

**Issue by skyminert** [levelkdev/dxswap-dapp#65]
I am providing Liquidity to the pair ZEENUS-XEENUS, yet it does not show as a pair in my pools.  

Link: https://gateway.pinata.cloud/ipfs/QmThpoPb2oLSevTH2sqw7wyHDJF1gXyvnoUCsjUsGEn8XF/#/pool

Pools:

![image](https://user-images.githubusercontent.com/57817726/97934947-04ba0b00-1d2c-11eb-9730-f13d51f30a26.png)

Proof: 
![image](https://user-images.githubusercontent.com/57817726/97934897-de946b00-1d2b-11eb-907a-763e28481097.png)

Augusto had some knowledge explain this.

**Comment by luzzif** [comment]
I think this might be outdated. The LP positions are shown only for tracked token pairs, i.e.:

- Those in which there's a base token (currently WETH, DAI, USDC and USDT)
- Those that are pinned (currently USDC/USDT, DAI/USDT and cDAI/cUSDT)
- User-saved pairs. This list is populated by the user when importing pools, and saved in the browser's local storage (so it is by no means permanent)

The only doubt that I have looking at these screenshots, is why the SPN/CHA position is shown, but maybe at the time there was a different configuration in-code.
Looking at Uniswap, that's how it should work there too.

An improvement that I might suggest is automatically saving a pair in the third category in the bullet list above when a user adds liquidity or creates a new pair. I don't see it as particularly detrimental to performance, and it's for sure nice to let a user immediately see their positions when adding liquidity instead of manually adding them later. Much more straight-forward.

This is not intended to replace the import pool function, since if someone deletes the browser's `localStorage`, they'd get right back to not seeing their "exotic" pools. But it's maybe an improvement. 

What do you think? @zamli @skyminert @jpkcambridge
