### ISSUE TITLE
Landing page issues 

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/dxswap-dapp#660]
Some open issues listed:
- Vote button doesnt work, would be good to take to Snapshot for now.
- Farm button takes to a different page and throws ipfs resolve error
- Swapr stats, anything to be fixed here, numbers are very vague (Keenan)
- All links under this stats are not available. would be good to fix them and make a new PR
- No links in Footer works
- Window resizes while opening the settings box https://gyazo.com/ee1c5a6fd413a58adf4fa52bd8fa01d0

**Comment by adamazad** [comment]
Different footer shade. 
  ![image](https://user-images.githubusercontent.com/1926216/154060149-caa80fde-4ddc-479e-a96d-7e9104f8498f.png)

**Comment by KeenanLukeOM** [comment]
Last batch of changes and should be complete! This includes the above.

- The vote feature button is not properly redirecting to the vote page. This is current external, so may make sense to simply point to the same URL? https://snapshot.org/#/swpr.eth
![image](https://user-images.githubusercontent.com/76129769/154111174-d53aebbd-da31-46e9-9be9-d4ef35c395c6.png)

- Both Farm and Bridge are not properly redirecting. It looks like they are pointing to `/bridge` instead of `/#/bridge`, for example.
![image](https://user-images.githubusercontent.com/76129769/154111509-f0d3aafc-d108-48bc-9485-7555cbc8abda.png)

- Making Swapr stats dynamic: Will this be a simple fix provided I can give information on the subgraphs and where to fetch this data? If so, please message me directly on telegram and I can get the info. If not, also reach out to me, and I can provide some updated stats that we can use raw for the time being.
![image](https://user-images.githubusercontent.com/76129769/154111728-de6b5c63-0427-4339-b161-765fb9eda88c.png)

- For the `DXdao product` section, correct `DXDao` to `DXdao`. Make the `Get Involved` button point to `https://dxdao.eth.link/`. Make the `Forum` button point to `https://daotalk.org/c/dx-dao/15`.
![image](https://user-images.githubusercontent.com/76129769/154112388-c1afc07c-a324-408c-bb83-03c101c03ae1.png)

- For the unstoppable community section: Change `tagline` to `Swapr Protocol`. Make `Join Discord` point to `https://discord.gg/4QXEJQkvHH`. Make `Visit Github` point to `https://github.com/levelkdev/dxswap-dapp`. Make `Follow On Twitter` point to `https://twitter.com/SwaprEth`
![image](https://user-images.githubusercontent.com/76129769/154113009-fb63a329-a917-4a8c-abab-f1ee12c8595e.png)

- For the blog, is this a dynamic function? It appears outdated and the links are not bringing to the respective blog post. If this currently is not dynamic, please reach out to me on Telegram, I can send over updated blog posts that we can use temporarily.
![image](https://user-images.githubusercontent.com/76129769/154113887-932f5765-6ca6-4e64-a605-8325c1911475.png)

- It looks like the footer does not have links, unsure if these were sent previously, but will share again here: Point `FAQ` to `https://dxdocs.eth.link/docs/Products/swapr/faq/`. Point `Blog` to `https://medium.com/swapr`. Point `Audits` to `https://dxdocs.eth.link/docs/Technical%20Documentation/Audits/#swapr`. Point `Brand Assets` to `https://dxdocs.eth.link/docs/BrandingAssets/#swapr-brand-assets`. Point `Discord` to `https://discord.gg/4QXEJQkvHH`. Point `Twitter` to `https://twitter.com/SwaprEth`. Point `Keybase` to `https://keybase.io/team/dx_dao`. Point `Forum` to `https://daotalk.org/c/dx-dao/15`. Point `DIY Liq. Mining` to `https://dxdocs.eth.link/docs/Products/swapr/DIY%20Liquidity%20Mining/`. Point `Roadmap` to `https://dxdocs.eth.link/docs/Products/swapr/roadmap/`. Point `We're Hiring` to `https://dxdocs.eth.link/docs/ContributorHub/open-positions-and-bounties/`. Point `Token` to `https://dxdocs.eth.link/docs/Products/swapr/tokenomics/`. Add `DXstats` underneath `Analytics` and point it to `https://dxstats.eth.link/#/home`
![image](https://user-images.githubusercontent.com/76129769/154115047-38783655-90b3-430c-8858-76f5401fd661.png)

**Comment by guidolarosa** [comment]
Hi @0xVenky, @KeenanLukeOM, @adamazad ! I managed to solve all these issues except for the one regarding the displacement of the window when opening the modals. There are some styles appended to the 'body' tag when opening the modals and I'm not sure where they are coming from. Could you help me with this?

<img width="279" alt="image" src="https://user-images.githubusercontent.com/15789977/154338943-74f6ee31-c128-4985-9da6-6aefc3081adc.png">

**Comment by 0xVenky** [comment]
Closing as this got released as part of Beta 11.
